### ISSUE TITLE
No reaction with cards of Tübingen-Hohenheim

### ISSUE THREAD

**Issue by bit-seq** [jakobwenzel/MensaGuthaben#11]
InterCard here. I am willing to provide the necessary information to get these cards supported.

**Comment by eliasp** [comment]
Can confirm. How can I provide the required debug information?

**Comment by jakobwenzel** [comment]
Please follow the steps outlined in https://jakobwenzel.github.io/MensaGuthaben/otherUnis.html

**Comment by jakobwenzel** [comment]
Hohenheim worked for me. Strange...

**Comment by bit-seq** [comment]
The card uses a **MIFARE Classic 1K** chip. A data dump with [NFC TagInfo](https://play.google.com/store/apps/details?id=at.mroland.android.apps.nfctaginfo) reveals sectors 0 to 15 that each list `Read failed! Read failed! Read failed! Read failed!`.

As [otherUnis.html](https://github.com/jakobwenzel/MensaGuthaben/blob/e4837af2f295e2ed6313ef7cc034096117165e65/docs/otherUnis.md) states, MensaGuthaben does not support Mifare Classic cards at this time, where patches are welcome.

I suggest to close this issue as my concern in is no longer relevant.

**Comment by jakobwenzel** [comment]
It seems that newer cards are DESFire cards. In the past, I successfully tested the app with a card that was issued in Oct 2015. 

I will add Hohenheim to the list with a note that only newer cards are supported.
