### ISSUE TITLE
App crashes when not opend

### ISSUE THREAD

**Issue by Weishaupt** [jakobwenzel/MensaGuthaben#13]
Since the update to Lollipop when I hold the card against the phone, the app opens up and crashes immediately. When I open the app and access the card afterwards, the amount is displayed, like it should. 

Nexus 4 with Vanilla Android 5.0.1 and the F-Droid Version of MensaGuthaben

**Comment by jakobwenzel** [comment]
Hi,

this should be fixed in the newest revision in git. However, it's not yet uploaded to the market, because there's some weird graphical issue in the new design.

Cheers,
Jakob

**Comment by jakobwenzel** [comment]
Finally pushed to Google Play.
