### ISSUE TITLE
Balance is not displayed for the "FH Karte" of FH Aachen

### ISSUE THREAD

**Issue by nicolasblume** [jakobwenzel/MensaGuthaben#16]
I am using a Galaxy S4 and tried to read the balance of the "FH Karte" of FH Aachen. 
With NFC active, the Card gets recognized with a sound and a window that should show the cards balance. 
But instead of the balance it always says: "Auf Mensakarte legen" 

![screenshot_2015-09-30-21-46-02](https://cloud.githubusercontent.com/assets/14913584/10204586/fbb83484-67bc-11e5-8ac8-6c4c97e6d4c8.png)

Is there a way to optimize the app for FH Aachen? The website "mensaguthaben.yazo-games.de" is not working, unfortunately...

**Comment by jakobwenzel** [comment]
Please follow the steps outlined in https://jakobwenzel.github.io/MensaGuthaben/otherUnis.html

**Comment by jakobwenzel** [comment]
Received the files. They are identical, so sadly, FH Aachen cannot be supported :(
