### ISSUE TITLE
Show balance in lock screen

### ISSUE THREAD

**Issue by floh1111** [jakobwenzel/MensaGuthaben#18]
I have an encrypted Smartphone so every time I want to check my balance I need to unlock the phone with my password. That takes more time than checking the balance at the Maschine used to load New money in the card.

Would it be possible to display the balance in the lock screen? As notificarion i.e.?

**Comment by jakobwenzel** [comment]
NFC seems to be disabled when the phone is locked, as there is no sound played when a card is detected and the phone is locked. There is nothing that I can do about it. Sorry :(
