### ISSUE TITLE
Fehlerhafter Link in der Google-Play-Beschreibung

### ISSUE THREAD

**Issue by berndtorino** [jakobwenzel/MensaGuthaben#26]
Kein direktes Problem mit der App an sich oder dem Quellcode, aber der Link (mensaguthaben.yazo-games.de) in der Google-Play-Beschreibung der App führt nicht auf eure Seite, sondern leitet auf eine Anwaltsberatung (http://wp.abc-anwalt.de/) weiter.

**Comment by jakobwenzel** [comment]
behoben
