### ISSUE TITLE
karte RWTH Aachen nicht unterstützt. 

### ISSUE THREAD

**Issue by silverches** [jakobwenzel/MensaGuthaben#8]
Die Karte der RWTH aachen funktioniert nicht. Die  brauchen auch magnakarta.

**Comment by TheRealKingS** [comment]
Selbe hier. Habe gerade mal versucht, die "Gast" Karte auszulesen. Wenn irgendwelche Informationen benötigt werden, einfach kurz melden.

**Comment by jakobwenzel** [comment]
Mehr Infos wie in https://jakobwenzel.github.io/MensaGuthaben/otherUnis.html beschrieben wären super

**Comment by TheRealKingS** [comment]
Ich habe die XML Dateien da. Sende sie dir per Mail.

**Comment by jakobwenzel** [comment]
Schlechte Nachricht: Die Dateien sind identisch, d.h. der Wert ist nicht lesbar gespeichert. Schade :(

**Comment by TheRealKingS** [comment]
Schade. Naja, kann man nichts machen.

Am 22.02.2017 6:23 nachm. schrieb "Jakob Wenzel" <notifications@github.com>:

**Comment by jakobwenzel** [comment]
Man kann beim Studierendenwerk anfragen. Weil das jetzt auch schon mehrmals kam hab ich einen Absatz in https://jakobwenzel.github.io/MensaGuthaben/otherUnis.html dazu geschrieben.
