### ISSUE TITLE
Karte: FAUcard der FAU Erlangen nicht unterstützt

### ISSUE THREAD

**Issue by sedrubal** [jakobwenzel/MensaGuthaben#9]
Die Karte vom Studentenwerk Erlangen Nürnberg nutzt die Mifare DESFire. Mehr Informationen gibt's hier: https://card.fau.de/

Wäre schön, wenn diese auch unterstützt werden würde ;)

**Comment by jakobwenzel** [comment]
Kannst du mehr Infos sammeln mit der Anleitung unter https://jakobwenzel.github.io/MensaGuthaben/otherUnis.html?

**Comment by sedrubal** [comment]
Das Guthaben scheint verschlüsselt auf der Karte zu liegen 😉
